/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jyvzyatnctgrnamqqrbk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5dnp5YXRuY3Rncm5hbXFxcmJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxNjk2NzgsImV4cCI6MjA4Nzc0NTY3OH0.xbj5Ih4HMlEPAfvVd-l3jSK1ZPVu9-89Vy1Pjzhymvg"